import Head from 'next/head';
import { About, Contact, Hero, Navbar, Partners } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Msportlinkafrica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Hero />
        <About />
        <Partners />
        <Contact />
      </div>
    </div>
  );
}
